server:
  port: 8090

spring:
  application:
    name: demo-bank-operations-hub-service
  cache:
    type: simple

demo:
  services:
    paymentsBaseUrl: http://localhost:8080
    accountBaseUrl:  http://localhost:8081
    ledgerBaseUrl:   http://localhost:8082
    limitsBaseUrl:   http://localhost:8083
    cardsBaseUrl:    http://localhost:8088

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
